name: build-bench-race
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  # This workflow would run at 1 AM every day
  schedule:
    - cron: '0 1 * * *'    
permissions:
  contents: read
jobs:
  build:
    if: github.event_name == 'push' || github.event_name == 'schedule'
    runs-on: [self-hosted, linux, x64]
    env:
      GOPROXY: https://proxy.golang.org,direct
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build
        run: make build && make build-plugins
  utests:
    if: github.event_name == 'push' || github.event_name == 'schedule'
    runs-on: [self-hosted, linux, x64]
    env:
      GOPROXY: https://proxy.golang.org,direct
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Unit test
        run: make utest
  race:
    if: github.event_name == 'pull_request' || github.event_name == 'schedule'
    runs-on: [self-hosted, linux, x64]
    env:
      GOPROXY: https://proxy.golang.org,direct
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Test race
        run: go test -count=1 -parallel 1 -race ./...
  bench:
    if: github.event_name == 'pull_request'
    runs-on: [self-hosted, linux, x64]
    env:
      GOPROXY: https://proxy.golang.org,direct
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Benchmark
        run: go test -bench=. -benchmem -run=^$ ./...
